apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: colormatic-deployer
  namespace: colormatic
subjects:
  - kind: Group
    # Name field should match the group configured in the
    # `allow.kubernetes_groups` of a role belonging to the user you wish to
    # grant access to.
    name: colormatic-deployer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: colormatic-deployer
  apiGroup: rbac.authorization.k8s.io