apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: colormatic
  name: colormatic
  namespace: colormatic
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: colormatic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: colormatic
    spec:
      containers:
        - image: ghcr.io/dumez-k/machineid-github-kubernetes-webinar/colormatic:latest
          name: colormatic
          ports:
            - containerPort: 9090
              protocol: TCP
          resources: {}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always