name: "Deploy Colormatic!"
on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: build-bot
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/colormatic:latest
            ghcr.io/${{ github.repository }}/colormatic:${{ github.sha }}
  deploy-to-kubernetes:
    name: Deploy Kubernetes manifests using Teleport and Kubectl
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
      - name: Install Teleport
        uses: teleport-actions/setup@v1
        with:
          version: 12.1.0
      - name: Authorize against Teleport
        uses: teleport-actions/auth-k8s@v1
        with:
          # Specify the publically accessible address of your Teleport proxy.
          proxy: root.tele.ottr.sh:443
          # Specify the name of the join token for your bot.
          token: colormatic-deployer
          # Specify the length of time that the generated credentials should be
          # valid for. This is optional and defaults to "1h".
          # Here we've limited it to 10m as this CI job doesn't need longer.
          certificate-ttl: 10m
          # Specify the name of the Kubernetes cluster you wish to access.
          kubernetes-cluster: docker-desktop
          # Enable submission of anonymous usage telemetry to Teleport.
          # See https://goteleport.com/docs/machine-id/reference/telemetry/ for
          # more information.
          anonymous-telemetry: 1
      - uses: azure/k8s-deploy@v4
        with:
          namespace: 'colormatic'
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
          images: 'ghcr.io/strideynet/machineid-github-kubernetes-webinar/colormatic:${{ github.sha }}'
